(async()=>{
  if(location.hostname!=='127.0.0.1'||location.pathname!=='/curriculum-admin-test')throw Error('Local harness required');
  const checks=[],assert=(ok,msg)=>{if(!ok)throw Error(msg);checks.push(msg);};
  const tick=()=>new Promise(r=>setTimeout(r,10));
  const until=async fn=>{for(let i=0;i<300;i++){if(fn())return;await tick();}throw Error('Timed out: '+fn);};
  const root=()=>document.querySelector('#mora-curriculum-admin'),form=()=>root()?.querySelector('form');
  const clickText=text=>{const b=[...root().querySelectorAll('button')].find(b=>b.textContent===text);if(!b)throw Error('Missing button '+text);b.click();};
  const field=(name,value)=>{const input=form().elements[name];input.value=value;input.dispatchEvent(new Event(name==='kind'?'change':'input',{bubbles:true}));};
  const submit=async()=>{form().requestSubmit();await until(()=>!root()?.textContent.includes('Saving…')&&!root()?.textContent.includes('Loading curriculum…'));};
  const open=async()=>{document.querySelector('#admin-tab-curriculum').click();await until(()=>root()?.querySelector('nav'));};
  const originalConfirm=window.confirm;let confirmations=0;window.confirm=()=>{confirmations++;return true;};
  try{
    await open();assert(root().textContent.includes('All modules'),'hierarchy and module catalog render');
    clickText('New semester');field('label','Synthetic semester');field('kind','departmental');await submit();
    const sem=testCatalog.semesters.find(r=>r.label==='Synthetic semester');assert(sem?.status==='draft'&&sem.id.startsWith('semester_'),'draft semester uses generated ID');
    root().querySelector('[data-create="departments"][data-parent="'+sem.id+'"]').click();field('label','Synthetic department');await submit();
    const dep=testCatalog.departments.find(r=>r.label==='Synthetic department');assert(dep?.semester_id===sem.id,'department created beneath selected semester');
    root().querySelector('[data-create="streams"][data-parent="'+dep.id+'"]').click();field('label','Synthetic stream');await submit();
    assert(testCatalog.streams.some(r=>r.department_id===dep.id),'stream created beneath selected department');
    clickText('New module');field('label','Synthetic new module');field('description','Only metadata');await submit();
    const mod=testCatalog.modules.find(r=>r.label==='Synthetic new module');assert(mod?.content_kind==='none'&&!testCatalog.placements.some(p=>p.module_id===mod.id),'new module remains unplaced without content');
    const before=testWrites.length;field('label','   ');await submit();assert(testWrites.length===before,'blank labels cannot write');
    field('label','Renamed draft');await submit();assert(testWrites.at(-1).p_patch.label==='Renamed draft'&&Object.keys(testWrites.at(-1).p_patch).length===1,'update includes only changed fields');
    root().querySelector('[data-record="math"]').click();field('label','Published correction');window.confirm=()=>false;await submit();
    assert(testCatalog.modules.find(m=>m.id==='math').label!=='Published correction','published correction can be cancelled');
    window.confirm=()=>true;await submit();assert(testCatalog.modules.find(m=>m.id==='math').label==='Published correction','published correction confirmed');
    assert([...root().querySelectorAll('[data-record="math"]')].every(b=>b.textContent.includes('Published correction')),'shared placements show one updated module');
    root().querySelector('[data-record="archived"]').click();assert(form().querySelector('[type="submit"]').disabled,'archived record read-only');
    root().querySelector('[data-record="empty"]').click();field('label','Unsaved');window.confirm=()=>false;document.querySelector('#admin-tab-settings').click();assert(!!form(),'cancel keeps unsaved form');
    window.confirm=()=>true;document.querySelector('#admin-tab-settings').click();assert(!root(),'confirmed tab change discards form');await open();
    clickText('New module');field('label','Lost before');const idText=form().textContent;testFailure='before';await submit();
    assert(form().querySelector('[type="submit"]').disabled,'uncertain save blocks blind retry');clickText('Reload and review');await until(()=>!root().textContent.includes('Loading curriculum…'));
    assert(form().textContent.includes(idText.match(/ID: ([a-z0-9_-]+)/)[1]),'retry retains generated ID');await submit();
    assert(testCatalog.modules.filter(m=>m.label==='Lost before').length===1,'retry creates one module');
    clickText('New module');field('label','Lost after');testFailure='after';await submit();const writes=testWrites.length;
    clickText('Reload and review');await until(()=>root().textContent.includes('Saved values confirmed'));
    assert(testWrites.length===writes&&testCatalog.modules.filter(m=>m.label==='Lost after').length===1,'lost acknowledgement reconciles without another write');
    field('label','My conflicting edit');testCatalog.revision++;await submit();assert(root().textContent.includes('Another edit'),'conflict requires review');
    clickText('Reload and review');await until(()=>!root().textContent.includes('Loading curriculum…'));assert(form().elements.label.value==='My conflicting edit','conflict preserves entered values');await submit();
    field('label','<img src=x onerror=alert(1)>');await submit();assert(!root().querySelector('img'),'labels render as text');
    testOnline=false;dispatchEvent(new Event('offline'));assert(form().querySelector('[type="submit"]').disabled,'offline writes disabled');testOnline=true;dispatchEvent(new Event('online'));
    let release;testWriteHook=()=>new Promise(r=>release=r);field('label','Single submit');form().requestSubmit();await tick();const count=testWrites.length;form().dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));assert(testWrites.length===count,'duplicate submit suppressed');release();testWriteHook=null;await until(()=>!root().textContent.includes('Saving…')&&!root().textContent.includes('Loading curriculum…'));
    testReadHook=()=>new Promise(r=>release=r);clickText('Retry / refresh');await tick();testAccount('student',false);release();testReadHook=null;await tick();assert(!root()&&document.getElementById('host').textContent.includes('Access denied'),'account switch clears drafts and rejects late reads');
    testAccount(null,false);assert(document.getElementById('host').textContent.includes('Access denied'),'guest denied');
    testAccount('admin',true);await open();testAdmin=false;MoraCurriculumAdmin.checkAccess();assert(!root(),'role revocation clears interface');testAccount('admin',true);await open();
    document.querySelector('#admin-tab-curriculum').dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true}));await tick();
    assert(document.activeElement.id==='admin-tab-statistics','keyboard Home restores statistics');
    document.querySelector('#admin-tab-statistics').dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));await until(()=>root()?.querySelector('nav'));
    assert(document.activeElement.id==='admin-tab-curriculum','keyboard End opens curriculum');
    let readCalls=0;testReadHook=async()=>{readCalls++;throw Error('missing RPC');};clickText('Retry / refresh');await until(()=>root().textContent.includes('Could not load'));
    const failedReads=readCalls;await tick();assert(readCalls===failedReads,'read failure is stable without automatic retry');testReadHook=null;clickText('Retry / refresh');await until(()=>!root().textContent.includes('Loading curriculum…'));assert(!root().textContent.includes('Could not load'),'explicit retry recovers');
    testReadHook=()=>new Promise(r=>release=r);clickText('Retry / refresh');await tick();document.querySelector('#admin-tab-settings').click();release();testReadHook=null;await tick();assert(!root()&&document.querySelector('#admin-panel').textContent==='Synthetic settings','late read cannot replace another tab');await open();
    const cache=JSON.parse(localStorage.getItem('mora_curriculum_v1:local-synthetic-admin'));assert(cache.visibility==='published'&&!cache.modules.some(m=>m.id===mod.id),'drafts absent from public cache');
    assert(!performance.getEntriesByType('resource').some(r=>/supabase|subject_data/.test(r.name)),'no hosted backend or real banks requested');
    return {passed:checks.length,checks,viewport:[innerWidth,innerHeight]};
  }finally{window.confirm=originalConfirm;testReadHook=null;testWriteHook=null;}
})();
